name: PR Testing & Validation
on:
  pull_request:
    branches:
      master
    paths:
      - install.sh
      - docs/**
      - .github/workflows/deploy.yml
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Prepare testing
        run: |
          chmod +x test.sh

      - name: Test scenarios
        run: |
          docker build -t atd_test:latest .
          docker run --rm -t atd_test generic
          docker run --rm -t atd_test atd
          docker run --rm -t atd_test toi
          docker run --rm -t atd_test dev
